# Data Quality Check - GitHub Actions Workflow
# Copy this file to your repo's .github/workflows/ directory.
# Docs: https://github.com/liuxiaotong/data-check#github-actions
#
# Configurable variables:
#   DATA_DIR:   Directory containing data files (default: "data")
#   THRESHOLD:  Minimum pass rate 0-1 (default: "0.5")
#   RULESET:    Rule set name (default: "default")

name: Data Quality Check

on:
  push:
    branches: [main]
    paths:
      - 'data/**'
  pull_request:
    branches: [main]
    paths:
      - 'data/**'
  workflow_dispatch:
    inputs:
      data_dir:
        description: 'Data directory to check'
        default: 'data'
      threshold:
        description: 'Minimum pass rate (0-1)'
        default: '0.5'

env:
  DATA_DIR: ${{ inputs.data_dir || 'data' }}
  THRESHOLD: ${{ inputs.threshold || '0.5' }}
  RULESET: default

jobs:
  quality-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install datacheck
        run: pip install knowlyr-datacheck

      - name: Run quality check
        id: check
        run: |
          knowlyr-datacheck check "$DATA_DIR" \
            --ruleset "$RULESET" \
            --threshold "$THRESHOLD" \
            --format json \
            --output quality-report.json
        continue-on-error: true

      - name: Generate markdown report
        if: always()
        run: |
          knowlyr-datacheck check "$DATA_DIR" \
            --ruleset "$RULESET" \
            --format markdown \
            --output quality-report.md

      - name: Upload report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: quality-report
          path: |
            quality-report.json
            quality-report.md

      - name: Post PR comment
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let body = '## Data Quality Report\n\n';
            try {
              const report = fs.readFileSync('quality-report.md', 'utf8');
              body += report.length > 60000
                ? report.substring(0, 60000) + '\n\n... (truncated)'
                : report;
            } catch (e) {
              body += '> Report generation failed. Check workflow logs.';
            }
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const botComment = comments.data.find(c =>
              c.body.includes('## Data Quality Report')
            );
            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body,
              });
            }

      - name: Fail if quality below threshold
        if: steps.check.outcome == 'failure'
        run: exit 1
